# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Wall•et' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CropViewController'
  pod 'Disk', '0.6.4'
  pod 'Kingfisher', '5.15.5'
  pod 'SVGKit', '2.1.1'
  pod 'SwiftMessages', '8.0.2'
  pod 'KeychainAccess'
  # Pods for Wall•et

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
